### ISSUE TITLE
Publishing provider does not work

### ISSUE THREAD

**Issue by Markwow** [vildanbina/laravel-versions#2]
Hi I am just running second command and it doesnt work:

php artisan vendor:publish --provider="VildanBina\LaravelVersions\DraftsServiceProvider"
INFO  No publishable resources for tag [].

**Comment by vildanbina** [comment]
@Markwow Thank you very much for informing me about this issue. There was a typo in the class name. The Readme.md has been updated. For a quicker resolution, please run the following command:
```bash
php artisan vendor:publish --provider="VildanBina\LaravelVersions\VersionsServiceProvider"
```

Let me know if you encounter any further issues!

**Comment by Markwow** [comment]
Thanks for the quick reply! Really looking forward to using this!
